/*using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Chirp.Models 
{
    [Table("Cheeps")]
    public class Cheep
    {
        [Display(Name = "Cheep ID")]
        [Key]
        public int CheepId { get; set; }
        public required Author Author { get; set; }
        public required string Text { get; set; }
        [DataType(DataType.Date)]
        public required DateTime TimeStamp { get; set; }
    }
}*/

//fix generated by chat, might be useless

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Chirp.Models
{
    [Table("Cheeps")]
    public class Cheep
    {
        [Display(Name = "Cheep ID")]
        [Key]
        public int CheepId { get; set; }

        [Required]
        public Author Author { get; set; }

        [Required]
        public string Text { get; set; }

        [DataType(DataType.Date)]
        [Required]
        public DateTime TimeStamp { get; set; }
    }
}
